# Generated by Django 3.2.9 on 2021-12-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appreciations',
            options={'verbose_name': 'Appreciations', 'verbose_name_plural': 'Appreciations'},
        ),
    ]
