# Generated by Django 3.2.9 on 2021-11-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256, verbose_name='intitule')),
                ('identifiant', models.CharField(max_length=50, verbose_name='identifiant')),
                ('pays', models.CharField(max_length=50, verbose_name='pays')),
                ('ville', models.CharField(max_length=50, verbose_name='ville')),
                ('addresse', models.CharField(max_length=50, verbose_name='addresse')),
                ('debut_partanariat', models.DateField(verbose_name='debut partenariat')),
                ('fin_partenariat', models.DateField(verbose_name='fin partenariat')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('encadreur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.encadreur')),
                ('poste', models.CharField(max_length=100, verbose_name='poste')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise', verbose_name='entreprise')),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employes',
            },
            bases=('user.encadreur',),
        ),
    ]
