# Generated by Django 3.2.9 on 2021-11-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=256, verbose_name='sujet')),
                ('date', models.DateTimeField(verbose_name='date et heure')),
                ('lieu', models.CharField(max_length=100, verbose_name='lieu')),
                ('rapport', models.TextField(verbose_name='resume')),
                ('compte_rendu', models.FileField(upload_to=None, verbose_name='compte rendu')),
                ('participants', models.ManyToManyField(to='user.User', verbose_name='participants')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.projetfindetudes', verbose_name='PFE')),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reunions',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=50, verbose_name='objet')),
                ('contenu', models.CharField(max_length=500, verbose_name='contenu')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='auteur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.projetfindetudes', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
