# Generated by Django 3.2.9 on 2021-11-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="date d'archivage")),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.soutenant', verbose_name='soutenant')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.projetfindetudes', verbose_name='PFE')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
            },
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('commentaire', models.CharField(max_length=256, verbose_name='commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.etudiant', verbose_name='auteur')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivage.rapport', verbose_name='rapport')),
            ],
            options={
                'verbose_name': 'Commentaires',
                'verbose_name_plural': 'Commentairess',
            },
        ),
    ]
