# Generated by Django 3.2.9 on 2021-11-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50, verbose_name='intitule')),
                ('domaine', models.CharField(max_length=50, verbose_name='domaine')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=256, verbose_name='intitule')),
                ('acronyme', models.CharField(max_length=5, verbose_name='acronyme')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('numero_etudiant', models.CharField(max_length=20, verbose_name='numero carte etudiant')),
                ('annee_d_entree', models.DateField(verbose_name="Annee d'entree")),
                ('competences', models.ManyToManyField(to='etude.Competence', verbose_name='competences')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.departement', verbose_name='departement')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='ProjetFinDetudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=500, verbose_name='sujet')),
                ('annee_academique', models.PositiveIntegerField(verbose_name='annee academique')),
                ('competences', models.ManyToManyField(to='etude.Competence', verbose_name='competences')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.departement', verbose_name='departement')),
                ('encadreurs', models.ManyToManyField(to='user.Encadreur', verbose_name='encadreurs')),
            ],
            options={
                'verbose_name': 'PFE',
                'verbose_name_plural': 'PFEs',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('encadreur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.encadreur')),
                ('specialite', models.CharField(max_length=50, verbose_name='specialite')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
                ('description', models.TextField(verbose_name='description')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.departement', verbose_name='departement')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
            },
            bases=('user.encadreur',),
        ),
        migrations.CreateModel(
            name='Soutenant',
            fields=[
                ('etudiant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etude.etudiant')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etude.projetfindetudes', verbose_name='PFE')),
            ],
            options={
                'verbose_name': 'Soutenant',
                'verbose_name_plural': 'Soutenants',
            },
            bases=('etude.etudiant',),
        ),
    ]
