# Generated by Django 3.2.9 on 2021-11-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='prenom')),
                ('nom', models.CharField(max_length=30, verbose_name='nom')),
                ('telephone', models.CharField(max_length=11, verbose_name='telephone')),
                ('mail', models.EmailField(max_length=254, verbose_name='mail')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
            options={
                'verbose_name': 'Useur',
                'verbose_name_plural': 'Useurs',
            },
        ),
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('matricule', models.CharField(max_length=50, verbose_name='matricule')),
            ],
            options={
                'verbose_name': 'Encadreur',
                'verbose_name_plural': 'Encadreurs',
            },
            bases=('user.user',),
        ),
    ]
